/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.bismih.server_chat_app.ui;

import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

import org.json.JSONArray;
import org.json.JSONObject;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.EnumMap;

import com.bismih.server_chat_app.components.Request;
import com.bismih.server_chat_app.constants.s;
import com.bismih.server_chat_app.network_.Client;
import com.bismih.server_chat_app.utils.JsonProcessor;
import com.bismih.server_chat_app.view.buttons.ButtonN;

/**
 *
 * @author bismih
 */
public class MainApp extends javax.swing.JFrame {

    private static JFrame frame;
    private static Client client;
    private static int user_id;
    private static JPanel pnl_elements_s;
    private static JPanel pnl_messages_s;
    private static int project_id_global;
    private boolean is_in_project = true;

    enum State {
        PROJECT, MSG
    };

    public MainApp(int id) {
        initComponents();

        pnl_elements_s = pnl_elements;
        pnl_messages_s = pnl_messages;
        lb_id.setText("id: " + id);
        user_id = id;
        frame = this;

        configuration();
    }

    private static void configuration() {
        client = new Client(MainApp::communication);
        client.start_client();
        client.send(JsonProcessor.get_project(user_id));

    }

    private static void communication(String msg) {
        System.out.println("MainApp communication: 60\n" + msg);
        Request request = Request.getRequest(msg);

        if (request.getCode().equals(s.GET_PROJECT)) {
            JSONArray jArr = new JSONArray(request.getResult());
            fill_elements(jArr);
        } else if (request.getCode().equals(s.GET_MSG)) {
            pnl_messages_s.removeAll();
            frame.revalidate();
            JSONArray jArr = new JSONArray(request.getResult());
            for (int i = 0; i < jArr.length(); i++) {
                JSONObject jObj2 = jArr.getJSONObject(i);
                String message = jObj2.getString("msg");
                int sender_id = jObj2.getInt(s.SENDER_ID);
                int receiver_id = jObj2.getInt(s.RECEIVER_ID);
                String a = new JSONObject(message).getString("msg");
                pnl_messages_s
                        .add(new JLabel("sender_id: " + sender_id + " receiver_id: " + receiver_id + " msg: " + a));
                System.out.println("main app get_msg" + "sender_id: " + sender_id + " receiver_id: " + receiver_id
                        + " msg: " + message);
                System.out.println(jArr.getJSONObject(i).getString("msg"));
            }
        }
        frame.revalidate();
        frame.repaint();
    }

    private static void fill_elements(JSONArray jArr) {
        ButtonN btn;
        String project_name;
        for (int i = 0; i < jArr.length(); i++) {
            project_name = jArr.getJSONObject(i).getString(s.PROJECT_NAME);
            int project_id = jArr.getJSONObject(i).getInt(s.PROJECT_ID);

            // projeler için buton ekleme
            btn = new ButtonN();
            btn.setText(project_name + " " + project_id);
            System.out.println(project_name + " " + project_id);

            // butonlara tıklanınca mesajları getirme
            btn.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent arg0) {
                    pnl_messages_s.removeAll();
                    client.send(JsonProcessor.get_msg(project_id, -1, user_id));
                    System.out.println("mesajlar temizlendi");
                    project_id_global = project_id;
                }

            });
            pnl_elements_s.add(btn);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_messages = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lb_project_name = new javax.swing.JLabel();
        pnl_elements_ = new javax.swing.JPanel();
        pnl_top_id_back = new javax.swing.JPanel();
        btn_back = new com.bismih.server_chat_app.view.buttons.ButtonN();
        lb_id = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnl_elements = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main App");
        setBackground(new java.awt.Color(204, 255, 204));

        pnl_messages.setBackground(new java.awt.Color(153, 255, 153));
        pnl_messages.setPreferredSize(new java.awt.Dimension(300, 426));

        lb_project_name.setText("Grup_ismi");
        lb_project_name.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lb_project_name)
                                .addContainerGap(238, Short.MAX_VALUE)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(lb_project_name)
                                .addContainerGap(16, Short.MAX_VALUE)));

        javax.swing.GroupLayout pnl_messagesLayout = new javax.swing.GroupLayout(pnl_messages);
        pnl_messages.setLayout(pnl_messagesLayout);
        pnl_messagesLayout.setHorizontalGroup(
                pnl_messagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_messagesLayout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(0, 0, 0)));
        pnl_messagesLayout.setVerticalGroup(
                pnl_messagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnl_messagesLayout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        pnl_elements_.setBackground(new java.awt.Color(255, 255, 153));
        pnl_elements_.setPreferredSize(new java.awt.Dimension(150, 450));

        btn_back.setText("<");
        btn_back.setFont(new java.awt.Font("Arial Black", 1, 13)); // NOI18N
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        lb_id.setText("id: ");

        javax.swing.GroupLayout pnl_top_id_backLayout = new javax.swing.GroupLayout(pnl_top_id_back);
        pnl_top_id_back.setLayout(pnl_top_id_backLayout);
        pnl_top_id_backLayout.setHorizontalGroup(
                pnl_top_id_backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnl_top_id_backLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(lb_id, javax.swing.GroupLayout.PREFERRED_SIZE, 56,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)));
        pnl_top_id_backLayout.setVerticalGroup(
                pnl_top_id_backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnl_top_id_backLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnl_top_id_backLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(lb_id)));

        pnl_elements.setLayout(new javax.swing.BoxLayout(pnl_elements, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(pnl_elements);

        javax.swing.GroupLayout pnl_elements_Layout = new javax.swing.GroupLayout(pnl_elements_);
        pnl_elements_.setLayout(pnl_elements_Layout);
        pnl_elements_Layout.setHorizontalGroup(
                pnl_elements_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pnl_top_id_back, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnl_elements_Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jScrollPane1)));
        pnl_elements_Layout.setVerticalGroup(
                pnl_elements_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnl_elements_Layout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addComponent(pnl_top_id_back, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jScrollPane1)
                                .addGap(2, 2, 2)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(pnl_elements_, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                .addGap(0, 0, 0)
                                .addComponent(pnl_messages, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                                .addGap(0, 0, 0)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pnl_elements_, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                        .addComponent(pnl_messages, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_backActionPerformed

    }// GEN-LAST:event_btn_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frame = new MainApp(3);
                frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.bismih.server_chat_app.view.buttons.ButtonN btn_back;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_id;
    private javax.swing.JLabel lb_project_name;
    private javax.swing.JPanel pnl_elements;
    private javax.swing.JPanel pnl_elements_;
    private javax.swing.JPanel pnl_messages;
    private javax.swing.JPanel pnl_top_id_back;
    // End of variables declaration//GEN-END:variables
}
