/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.bismih.server_chat_app.ui;

import java.awt.event.ActionListener;

import javax.swing.JFrame;
import javax.swing.JLabel;

import org.json.JSONArray;
import org.json.JSONObject;

import com.bismih.server_chat_app.network_.Client;
import com.bismih.server_chat_app.utils.JsonProcessor;
import com.bismih.server_chat_app.view.buttons.ButtonN;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialDeepOceanIJTheme;

import netscape.javascript.JSObject;

/**
 *
 * @author bismih
 */
public class MainApp extends javax.swing.JFrame {

    private static Client client;
    private static JFrame frame;
    private static javax.swing.JPanel pnl_left1;
    private static javax.swing.JPanel scrl_msg_s;
    private static int user_id;
    private static int project_id_global;

    // TODO: sürekli yeni mesaj varmı kontrolü
    // yapan bir fonksiyon theradi ekle
    public MainApp(int id) {
        initComponents();
        user_id = id;
        addElements();
        configuration();
    }
    
    private void addElements() {
        pnl_left1 = pnl_left;
        scrl_msg_s = pnl_msg;

        //panel içindeki butonun eventini tetikleyen fonksiyon
        send_panel.get_btn_send().addActionListener((ActionListener) new ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                String msg = send_panel.get_tx_msg().getText();
                client.send(JsonProcessor.send_msg(msg, "text", -1, user_id, project_id_global));
                System.out.println(msg);
                send_panel.get_tx_msg().setText("");
            }
        });
        
    }

    private void configuration() {
        lb_id.setText(" id: " + user_id);
        client = new Client(MainApp::communication);
        client.start_client();
        client.send(JsonProcessor.get_project(user_id));
    }

    private static void communication(String msg) {
        System.out.println("MainApp communication:\n" + msg);
        JSONObject jObj = new JSONObject(msg);
        String code = jObj.getString("code");
        String result = jObj.getString("result");
        System.out.println("code: " + code + " result: " + result);

        JSONArray jArr;
        if (code.equals("get_project")) {
            jArr = new JSONArray(result);
            ButtonN buttonN;
            for (int i = 0; i < jArr.length(); i++) {
                JSONObject jObj2 = jArr.getJSONObject(i);
                buttonN = new ButtonN();
                String project_name = jObj2.getString("name");
                int project_id = jObj2.getInt("project_id");
                // buttonN.privateText = new int[] { project_id, -1, user_id};
                
                buttonN.setText("proje: "+project_id + " " + project_name);
                buttonN.addActionListener((ActionListener) new ActionListener() {
                    @Override
                    public void actionPerformed(java.awt.event.ActionEvent e) {
                        client.send(JsonProcessor.get_msg(project_id, -1, user_id));
                        scrl_msg_s.removeAll();
                        System.out.println("mesajlar temizlendi");
                        project_id_global = project_id;
                    }
                });

                pnl_left1.add(buttonN);
            }
        } else if (code.equals("get_msg")) {
            jArr = new JSONArray(result);
            for (int i = 0; i < jArr.length(); i++) {
                JSONObject jObj2 = jArr.getJSONObject(i);
                String message = jObj2.getString("msg");
                int sender_id = jObj2.getInt("sender_id");
                int receiver_id = jObj2.getInt("receiver_id");
                String a =  new JSONObject(message).getString("msg");
                scrl_msg_s.add(new JLabel("sender_id: " + sender_id + " receiver_id: " + receiver_id + " msg: " + a));
                System.out.println("main app get_msg"+"sender_id: " + sender_id + " receiver_id: " + receiver_id + " msg: " + message);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        pnl_left = new javax.swing.JPanel();
        lb_id = new javax.swing.JLabel();
        pnl_right = new javax.swing.JPanel();
        scrl_msg = new javax.swing.JScrollPane();
        pnl_msg = new javax.swing.JPanel();
        send_panel = new com.bismih.server_chat_app.view.TextField.send_panel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        pnl_left.setBackground(new java.awt.Color(204, 255, 255));
        pnl_left.setPreferredSize(new java.awt.Dimension(100, 300));
        pnl_left.setLayout(new javax.swing.BoxLayout(pnl_left, javax.swing.BoxLayout.Y_AXIS));

        lb_id.setText("id:");
        pnl_left.add(lb_id);

        jSplitPane1.setLeftComponent(pnl_left);

        pnl_right.setBackground(new java.awt.Color(204, 255, 204));
        pnl_right.setPreferredSize(new java.awt.Dimension(500, 300));
        pnl_right.setLayout(new javax.swing.BoxLayout(pnl_right, javax.swing.BoxLayout.Y_AXIS));

        scrl_msg.setPreferredSize(new java.awt.Dimension(100, 300));

        pnl_msg.setBackground(new java.awt.Color(255, 255, 153));
        pnl_msg.setLayout(new javax.swing.BoxLayout(pnl_msg, javax.swing.BoxLayout.Y_AXIS));
        scrl_msg.setViewportView(pnl_msg);

        pnl_right.add(scrl_msg);
        pnl_right.add(send_panel);

        jSplitPane1.setRightComponent(pnl_right);

        getContentPane().add(jSplitPane1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // [60,63,65]
                FlatMaterialDeepOceanIJTheme.setup();
                frame = new MainApp(3);
                frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lb_id;
    private javax.swing.JPanel pnl_left;
    private javax.swing.JPanel pnl_msg;
    private javax.swing.JPanel pnl_right;
    private javax.swing.JScrollPane scrl_msg;
    private com.bismih.server_chat_app.view.TextField.send_panel send_panel;
    // End of variables declaration//GEN-END:variables
}
