/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.bismih.server_chat_app.view.TextField;

import com.bismih.server_chat_app.view.buttons.ButtonN;

/**
 *
 * @author bismih
 */
public class SendPanel extends javax.swing.JPanel {

    
    public SendPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tx_msg = new com.bismih.server_chat_app.view.TextField.TextFeild1();
        btn_send = new com.bismih.server_chat_app.view.buttons.ButtonN();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.X_AXIS));

        tx_msg.setText("Mesajınızı yazınız");
        add(tx_msg);

        btn_send.setText(" > ");
        btn_send.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        btn_send.setPreferredSize(new java.awt.Dimension(50, 40));
        add(btn_send);
    }// </editor-fold>//GEN-END:initComponents


    public ButtonN get_btn_send(){
        return btn_send;
    }
    
    public TextFeild1 get_tx_msg(){
        return tx_msg;
    }

    public void clear(){
        tx_msg.setText("");
    }

    public String get_msg(){
        return tx_msg.getText();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.bismih.server_chat_app.view.buttons.ButtonN btn_send;
    private com.bismih.server_chat_app.view.TextField.TextFeild1 tx_msg;
    // End of variables declaration//GEN-END:variables
}
